#loading packages
options(repos = BiocManager::repositories())
library(BiocManager)
library(shiny)
library(edgeR)
library(RColorBrewer)
library(ggplot2)
library(tidyverse)
library(shinyjs)
library(DT)
library(org.Hs.eg.db)
library(reshape)

#loading functions
source('./functions/build_frame.R')
source('./functions/check_col_number.R')
source('./functions/convert_ids.R')
source('./functions/find_overlaps.R')
source('./functions/generate_CDS.R')
source('./functions/get_genes_list.R')
source('./functions/get_row_names.R')
source('./functions/make_barplot.R')
source('./functions/make_bcv_plot.R')
source('./functions/make_boxplot.R')
source('./functions/make_compare_plot.R')
source('./functions/make_hist.R')
source('./functions/make_meanvar_plot.R')
source('./functions/make_results.R')
source('./functions/make_smear_plot.R')
source('./functions/plot_wrapper.R')
source('./functions/preprocess_data.R')
source('./functions/remove_low_counts.R')
source('./functions/transform_data.R')

#setting up variables
plots <- c("Bar", "Box", "BCV", "Mean-Var", "Histogram", "Smear")
